"""initial schema

Revision ID: ad1aecf9f82f
Revises: 
Create Date: 2026-03-20 12:53:32.969666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1aecf9f82f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_top_songs', sa.Column('spotify_url', sa.Text(), nullable=True))
    op.add_column('user_top_songs', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('user_top_songs', sa.Column('artist_name', sa.Text(), nullable=True))
    op.add_column('user_top_songs', sa.Column('track_title', sa.Text(), nullable=True))
    op.add_column('user_top_songs', sa.Column('album_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_top_songs', 'album_title')
    op.drop_column('user_top_songs', 'track_title')
    op.drop_column('user_top_songs', 'artist_name')
    op.drop_column('user_top_songs', 'image_url')
    op.drop_column('user_top_songs', 'spotify_url')
    # ### end Alembic commands ###
