"""Record ingest failures on user_top_songs so a failed seed stops being retried

Gameplan 10.5. Before this, a seed whose download failed stayed `song_id IS NULL`
forever, which `snapshot_is_stale` reads as "needs rebuilding" — so every request
re-fetched the user's top tracks from Spotify, wiped and rewrote the seed set, and
re-ran the whole failing ingest. An infinite loop, invisible because the failures are
`logger.warning`, not exceptions.

These three columns give a failure somewhere to live so it can become terminal after a
bounded number of attempts.

**Hand-written, not autogenerated.** Prod carries constraint-name drift that does not
exist in the baseline (`songs_album_id_title_key` vs `uq_songs_album_id_title`, and the
same for `albums_url_key`), so `--autogenerate` against prod folds in four spurious
constraint operations, one of which rebuilds a unique index over 110k rows under a lock.
See gameplan 10.1.

No index is added. `user_top_songs` has ~20 rows and no index beyond the primary key;
a partial index on pending rows would cost maintenance and buy nothing the planner uses.

Revision ID: c3d4e5f6a7b8
Revises: 45f91add221e
Create Date: 2026-09-25
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = '45f91add221e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required, not cosmetic: adding a NOT NULL column to a table that
    # already has rows fails without one. Postgres 11+ stores it in the catalog, so there
    # is no table rewrite. The model carries the same server_default so the two cannot
    # drift — env.py does not set compare_server_default, so Alembic would not warn.
    op.add_column(
        'user_top_songs',
        sa.Column('ingest_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # Set once the attempt cap is reached. NULL means "still eligible to be retried",
    # which is exactly what snapshot_is_stale keys off.
    op.add_column('user_top_songs', sa.Column('ingest_failed_at', sa.DateTime(), nullable=True))
    # The last failure reason, kept short, for showing the user why a seed is missing
    # and for debugging without digging through container logs.
    op.add_column('user_top_songs', sa.Column('ingest_error', sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column('user_top_songs', 'ingest_error')
    op.drop_column('user_top_songs', 'ingest_failed_at')
    op.drop_column('user_top_songs', 'ingest_attempts')
