"""Add claimed_at to user_top_songs so an external worker can lease a seed

Gameplan 10.6. The audio download has to move off EC2 — YouTube bot-challenges the
instance's datacenter IP and no configuration change fixes it (10.3) — so a worker on a
residential connection polls `/api/v1/ingest/claim` for seeds to process.

A claim needs somewhere to live, and it needs to expire. Without a lease column, two
workers (or the same worker restarted) would both download the same track, and a worker
that dies mid-job would leave a row that is neither pending nor failed: `song_id IS NULL`
and `ingest_failed_at IS NULL` forever, which is precisely the stuck state 10.5 just
finished removing.

`claimed_at` is nullable, so no server_default is needed and no backfill happens: every
existing row reads as unclaimed, which is correct.

**Hand-written, not autogenerated,** for the same reason as c3d4e5f6a7b8: prod carries
constraint-name drift that does not exist in the baseline, so `--autogenerate` against it
folds in four spurious constraint operations, one of which rebuilds a unique index over
110k rows under a lock. See gameplan 10.1.

No index. `user_top_songs` has ~20 rows; the claim query's `ORDER BY id LIMIT n` is
served fine by a sequential scan and a partial index would only cost maintenance.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-09-25
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Written by Postgres `now()` at claim time, never by Python. The lease comparison
    # happens entirely in SQL (`claimed_at < now() - interval`), so the column never has
    # to agree with a clock on the worker's machine — which is in PDT and would otherwise
    # be seven hours off. NULL means unclaimed.
    op.add_column('user_top_songs', sa.Column('claimed_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    op.drop_column('user_top_songs', 'claimed_at')
