"""Let a user exist without Spotify, and make seeds unique per user

Put You On 0.0.1, item A1. Today `users.spotify_id` is NOT NULL, so a row literally cannot
exist without a Spotify account. 0.0.1 adds email + password and Google sign-in, so the
row needs somewhere to keep each provider's identity and a record of which one owns it.

What this does, and why each piece is shaped the way it is:

- `spotify_id` becomes nullable. It stays unique; Postgres allows any number of NULLs.
- `google_id` holds Google's stable `sub` claim, unique under a constraint we name, so a
  later migration never has to guess an auto-generated name.
- `password_hash` holds an argon2id hash (0.0.1 A2). Never the password, never reversible.
- `auth_provider` records which path owns the account. A Postgres enum, created
  explicitly below: `op.add_column` does not create enum types, unlike the
  `op.create_table` that created `work_status_enum` in the baseline. Its server default
  is 'spotify', which covers the existing rows and keeps `upsert_user` (which never sets
  it) working until the Spotify login is retired in 0.0.1 Phase D.
- `email_verified` ships now and gates nothing yet; email confirmation comes later.
- Emails are lowercased, and a unique index on `lower(email)` makes the database refuse
  case variants even if some code path forgets to normalize. Email is the identity key
  from 0.0.1 on, so `Foo@x.com` and `foo@x.com` must never be two accounts. The existing
  `users_email_key` constraint is left alone: it is redundant alongside the lower(email)
  index, but dropping it would mean naming a constraint we did not name.
- `user_top_songs` gets a unique (user_id, spotify_track_id) constraint. Spotify's top
  tracks never repeat, but 0.0.1's picks can (a double click, two tabs).

Both data checks run before anything changes and report counts only. A failed migration
prints into the deploy log, whose tail is shown in this public repo's Actions logs, so
an email address must never appear in the message. The whole upgrade runs in one
transaction (alembic/env.py), so a failed check leaves the database exactly as it was.

**Hand-written, not autogenerated,** for the same reason as c3d4e5f6a7b8: prod carries
constraint-name drift that does not exist in the baseline, so `--autogenerate` against
it folds in spurious drop-and-recreate operations. See deployment-gameplan 10.1.

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-10-09
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e5f6a7b8c9d0'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


AUTH_PROVIDERS = ('email', 'google', 'spotify')


def _count(sql: str) -> int:
    return op.get_bind().execute(sa.text(sql)).scalar()


def upgrade() -> None:
    bind = op.get_bind()

    # The deploy runs this while the old backend is still serving. Several statements
    # below need an ACCESS EXCLUSIVE lock on users or user_top_songs, and get_recs holds a
    # user row lock across a Spotify call that can take up to 10 seconds; every request
    # that arrives meanwhile queues behind the waiting migration. Better to fail the deploy
    # after 5 seconds, loudly and with nothing changed, and re-run it. LOCAL scopes the
    # setting to this transaction.
    op.execute("SET LOCAL lock_timeout = '5s'")

    # Checks first, so nothing has changed if either fails. Counts only, never values:
    # see the docstring on why an email must not reach the deploy log.
    case_duplicates = _count(
        "SELECT count(*) FROM ("
        " SELECT lower(email) FROM users WHERE email IS NOT NULL"
        " GROUP BY lower(email) HAVING count(*) > 1"
        ") AS d"
    )
    if case_duplicates:
        raise RuntimeError(
            f"Cannot lowercase emails: {case_duplicates} address(es) are shared by more "
            "than one user once case is ignored. Resolve those accounts by hand, then "
            "re-run."
        )
    duplicate_seeds = _count(
        "SELECT count(*) FROM ("
        " SELECT user_id, spotify_track_id FROM user_top_songs"
        " GROUP BY user_id, spotify_track_id HAVING count(*) > 1"
        ") AS d"
    )
    if duplicate_seeds:
        raise RuntimeError(
            f"Cannot make seeds unique: {duplicate_seeds} (user, track) pair(s) appear "
            "more than once in user_top_songs. Delete the extra rows, then re-run."
        )

    op.execute("UPDATE users SET email = lower(email) WHERE email <> lower(email)")
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)

    op.alter_column('users', 'spotify_id', existing_type=sa.Text(), nullable=True)

    op.add_column('users', sa.Column('google_id', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])

    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))

    # Created explicitly: add_column, unlike create_table, never emits CREATE TYPE.
    # checkfirst so a re-run after a partial manual repair doesn't trip over it.
    postgresql.ENUM(*AUTH_PROVIDERS, name='auth_provider_enum').create(bind, checkfirst=True)
    # server_default is required, not cosmetic: adding a NOT NULL column to a table with
    # rows fails without one. 'spotify' is also the truth for every existing row.
    op.add_column(
        'users',
        sa.Column(
            'auth_provider',
            postgresql.ENUM(*AUTH_PROVIDERS, name='auth_provider_enum', create_type=False),
            nullable=False,
            server_default='spotify',
        ),
    )

    # False for the existing Spotify rows too: Spotify gave us those addresses, we never
    # confirmed them. A Google sign-in that links onto a row sets it (0.0.1 A6).
    op.add_column(
        'users',
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )

    op.create_unique_constraint(
        'uq_user_top_songs_user_track', 'user_top_songs', ['user_id', 'spotify_track_id']
    )


def downgrade() -> None:
    # spotify_id goes back to NOT NULL, which is impossible once an email or Google user
    # exists. Say so plainly instead of letting ALTER TABLE fail with a constraint error.
    # Past that point, rolling back means restoring the pre-migration snapshot.
    without_spotify = _count("SELECT count(*) FROM users WHERE spotify_id IS NULL")
    if without_spotify:
        raise RuntimeError(
            f"Cannot downgrade: {without_spotify} user(s) have no Spotify id, and "
            "spotify_id would become NOT NULL again. Restore the pre-migration snapshot "
            "instead."
        )

    op.drop_constraint('uq_user_top_songs_user_track', 'user_top_songs', type_='unique')

    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'auth_provider')
    postgresql.ENUM(name='auth_provider_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'password_hash')

    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_column('users', 'google_id')

    op.alter_column('users', 'spotify_id', existing_type=sa.Text(), nullable=False)

    # Emails stay lowercase: the original case was not kept anywhere.
    op.drop_index('uq_users_email_lower', table_name='users')
