events {}
http {
  server {
    listen 443 ssl;
    ssl_certificate /certs/localhost+1.pem;
    ssl_certificate_key /certs/localhost+1-key.pem;

    # Frontend
    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
    }

    # Backend API
    location /api/ {
      proxy_pass http://backend:8000;
      proxy_set_header Host $host;
    }
  }
}
